#!/bin/sh

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
TARGET_BRANCH=${CURRENT_BRANCH%-test}

CUSTOMIZATION_BRANCHES=$(git for-each-ref --format="%(refname)" "refs/remotes/**/$TARGET_BRANCH-customizations/*")

if [ -z "$CUSTOMIZATION_BRANCHES" ]; then
    echo "There are no customizations for branch '$TARGET_BRANCH', aborting."
    exit 1
fi

echo "Merging '$CUSTOMIZATION_BRANCHES' into '$CURRENT_BRANCH'..."

git reset --hard origin/master
git for-each-ref --format='%(refname)' refs/remotes/internal/ort-pipeline-customizations | xargs -n1 git merge --no-ff
