#!/bin/sh

UPSTREAM_BRANCH=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
TARGET_BRANCH=${CURRENT_BRANCH%-test}

CUSTOMIZATION_BRANCHES=$(git for-each-ref --format="%(refname)" "refs/remotes/**/$TARGET_BRANCH-customizations/*")

if [ -z "$CUSTOMIZATION_BRANCHES" ]; then
    echo "There are no customizations for branch '$TARGET_BRANCH', aborting."
    exit 1
fi

echo "Resetting branch to '$UPSTREAM_BRANCH'..."
git reset --hard $UPSTREAM_BRANCH

echo "Merging the following branches into '$CURRENT_BRANCH'..."
for BRANCH in $CUSTOMIZATION_BRANCHES; do
    echo $BRANCH
done

git merge --no-ff $CUSTOMIZATION_BRANCHES
