#!/bin/sh

# This script calculates the Git-style SHA1 for a blob / file like "git hash-object $1" does.

infile=$1
outfile=$(mktemp)

if !(dos2unix -n "$infile" "$outfile" 2>&1 | grep -q "Skipping binary file"); then
    infile=$outfile
fi

(stat --printf="blob %s\0" "$infile"; cat "$infile") | sha1sum -b | cut -d" " -f1

rm -f "$outfile"
